[target.x86_64-unknown-linux-gnu]
image = "docker.io/library/sfs-rs-build:latest"
pre-build = [
    "apt-get update && apt-get install -y libssl-dev apt-utils libgtk-3-dev",
    "printenv",
]

[build.env]
passthrough = ["STEAM_API"]
